name: Deploy to Minikube using GitHub Actions

on: [push]
  
jobs:
  job1:
    runs-on: ubuntu-24.04
    name: build Node.js Docker Image and deploy to minikube
    steps:
    - uses: actions/checkout@v4
    - name: Start minikube
      uses: medyagh/setup-minikube@v0.0.16
    - name: Try the cluster !
      run: kubectl get pods -A
    - name: Build image
      run: |
          export SHELL=/bin/bash
          eval $(minikube -p minikube docker-env)
          docker build -t nodejs-app:${{ github.sha }} .
          docker images
    - name: Deploy to minikube
      run: |
        kubectl apply -f k8s-node-app.yaml
        kubectl wait --for=condition=ready pod -l app=nodejs-app
    - name: Wait for deployment to be ready
      run: |
        kubectl set image deployment/nodejs-app nodejs-app=devopshint/node-app:latest
        kubectl rollout status deployment/nodejs-app --timeout=180s
        kubectl get pods -o wide
    - name: Test service URLs
      run: |
          minikube service list
          URL=$(minikube service nodejs-app --url | head -1)
          until curl -f -s $URL >/dev/null; do sleep 1; printf "."; done
          echo -e "\nApp is UP! $URL"
