name: Deploy to Minikube using GitHub Actions

on: [push]
  
jobs:
  job1:
    runs-on: ubuntu-24.04
    name: build Node.js Docker Image and deploy to minikube
    steps:
    - uses: actions/checkout@v4
    - name: Start minikube
      uses: medyagh/setup-minikube@v0.0.16
    - name: Try the cluster !
      run: kubectl get pods -A
    - name: Build image
      run: |
          eval $(minikube -p minikube docker-env)
      docker build -f ./Dockerfile -t nodejs-app:${{ github.sha::7 }} .
          docker images        
    - name: Deploy to minikube
      run:
        kubectl apply -f k8s-node-app.yaml
        kubectl wait --for=condition=ready pod -l app=nodejs-app
    - name: Wait for deployment to be ready
      run: |
        kubectl rollout status deployment/nodejs-app --timeout=180s
        kubectl get pods -o wide
    - name: Test service URLs
      run: |
          minikube service list
          SERVICE_STATUS=$(minikube service nodejs-app --url)
          until curl -fSs "$SERVICE_STATUS"; do
              echo "Service not started"
              sleep 3
          done
          echo "Service started"
